# Generated by Django 2.2.6 on 2019-11-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ali', '0006_auto_20191101_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ali_edit',
        ),
        migrations.AlterModelOptions(
            name='ali_prepare',
            options={'verbose_name': '准备保存列表', 'verbose_name_plural': '准备保存展示'},
        ),
        migrations.RemoveField(
            model_name='ali_prepare',
            name='showimg',
        ),
        migrations.AddField(
            model_name='ali',
            name='type',
            field=models.CharField(default=None, max_length=300, verbose_name='状态'),
        ),
    ]
