# Generated by Django 2.2.6 on 2019-11-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ali', '0003_ali_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ali',
            name='showimg',
            field=models.TextField(default=None, verbose_name='展示图片'),
        ),
        migrations.AddField(
            model_name='ali',
            name='type',
            field=models.CharField(default=None, max_length=300, verbose_name='状态'),
        ),
    ]
