# Generated by Django 2.2.6 on 2019-10-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=300, verbose_name='商品ID')),
                ('data', models.TextField(verbose_name='商品信息')),
            ],
            options={
                'verbose_name': '商品列表',
                'verbose_name_plural': '商品列表展示',
            },
        ),
    ]
