# Generated by Django 2.2.6 on 2019-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ali',
            name='title',
            field=models.TextField(default=None, verbose_name='标题'),
        ),
    ]
