# Generated by Django 2.2.6 on 2019-10-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ali', '0002_ali_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ali_Prepare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=300, verbose_name='商品ID')),
                ('data', models.TextField(verbose_name='商品信息')),
                ('title', models.TextField(default=None, verbose_name='标题')),
            ],
            options={
                'verbose_name': '准备保存列表',
                'verbose_name_plural': '准备保存展示',
            },
        ),
    ]
