# Generated by Django 2.2.6 on 2019-11-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ali', '0004_auto_20191101_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ali_edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=300, verbose_name='商品ID')),
                ('data', models.TextField(verbose_name='商品信息')),
                ('title', models.TextField(default=None, verbose_name='标题')),
                ('showimg', models.TextField(default=None, verbose_name='展示图片')),
            ],
            options={
                'verbose_name': '修改商品列表',
                'verbose_name_plural': '修改商品列表展示',
            },
        ),
        migrations.RemoveField(
            model_name='ali',
            name='type',
        ),
    ]
